# filename: deployment/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer_summary
  labels:
    app: news_summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news_summary
  template:
    metadata:
      labels:
        app: news_summary
    spec:
      containers:
        - name: news_summary
          image: pafruchtenreich/app:latest  
          ports:
            - containerPort: 8000
